//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tapanyagok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapanyag
    {
        public int id { get; set; }
        public string nev { get; set; }
        public decimal energia { get; set; }
        public decimal feherje { get; set; }
        public decimal zsir { get; set; }
        public decimal szenhidrat { get; set; }
    }
}
